version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_URI: "043309328819.dkr.ecr.us-east-1.amazonaws.com/exercise-hello-repo"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo "Generating Docker image tag..."
      - |
        if [ -z "$CODEBUILD_RESOLVED_SOURCE_VERSION" ]; then
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        else
          IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        fi
      - echo "Using image tag: $IMAGE_TAG"
      - export IMAGE_TAG
  build:
    commands:
      - echo "Build started on $(date)"
      - cd app
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO_URI}:${IMAGE_TAG} -t ${ECR_REPO_URI}:latest .
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker images..."
      - docker push ${ECR_REPO_URI}:${IMAGE_TAG}
      - docker push ${ECR_REPO_URI}:latest
      - echo "Writing imagedefinitions.json file..."
      - printf '[{"name":"exercise-hello-service","imageUri":"%s"}]' ${ECR_REPO_URI}:${IMAGE_TAG} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
